<%@ Page Language="C#" MasterPageFile="~/Site.Master" title="Category" AutoEventWireup="true" CodeBehind="Category.aspx.cs" Inherits="ShadyBusiness.CategoryForm" %>

<asp:Content ID="Category" ContentPlaceHolderID="MainContent" runat="server">
    <div class="pt-3">
        <h3>Category Form</h3><br />
        <div class="form-group">
            <label>Category</label>
            <asp:TextBox ID="txtCategory" runat="server" CssClass="form-control" placeholder="Aviator" ValidationGroup="valCategory"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ErrorMessage="Please enter text only" CssClass="alert-danger" ValidationExpression="^[a-zA-Z_ ]*$" ValidationGroup="valCategory" ControlToValidate="txtCategory"></asp:RegularExpressionValidator><br/>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="*required" CssClass="alert-danger" ControlToValidate="txtCategory" ValidationGroup="valCategory"></asp:RequiredFieldValidator>
        </div>
        <asp:Button ID="btnSubmit" runat="server" Text="     ADD CATEGORY     " CssClass="btn btn-primary float-right" OnClick="btnSubmit_Click" ValidationGroup="valCategory" />
    </div>
    <br /><br /><hr/><br />
    <b style="font-size:24px;">View Categories</b><br /><br />
    <div>
        <asp:GridView ID="GridView1" CssClass="table table-striped  table-bordered" runat="server"
            DataKeyNames="category_id"
            EmptyDataText="No records has been added."
            OnRowDataBound="GridView1_RowDataBound"
OnRowEditing="GridView1_RowEditing"
            OnRowDeleting="GridView1_RowDeleting"
            OnRowUpdating="GridView1_RowUpdating"
            OnRowCancelingEdit="GridView1_RowCancelingEdit"
            AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
        </asp:GridView>
        <%--<asp:SqlDataSource ID="dsCategory" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionStringSB %>" ProviderName="<%$ ConnectionStrings:ConnectionStringSB.ProviderName %>" SelectCommand="SELECT * FROM [category]"></asp:SqlDataSource>--%>
    </div>
</asp:Content>