<%@ Page Language="C#" MasterPageFile="~/Site.Master" title="Category" AutoEventWireup="true" CodeBehind="Category.aspx.cs" Inherits="ShadyBusiness.CategoryForm" %>

<asp:Content ID="Category" ContentPlaceHolderID="MainContent" runat="server">
    <div class="pt-3">
        <h3>Category</h3>
        <div class="form-group">
            <label>Category</label>
            <asp:TextBox ID="txtCategory" runat="server" CssClass="form-control" placeholder="Aviator" ValidationGroup="valCategory"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="Category required!" ControlToValidate="txtCategory" ForeColor="Red" ValidationGroup="valCategory"></asp:RequiredFieldValidator>
        </div>
        <asp:Button ID="btnSubmit" runat="server" Text="Insert" CssClass="btn btn-primary" OnClick="btnSubmit_Click" ValidationGroup="valCategory" />
    </div>
    <div>
        <asp:GridView ID="GridView1" CssClass="table table-hover" runat="server"
            DataKeyNames="category_id"
            EmptyDataText="No records has been added."
            OnRowDataBound="GridView1_RowDataBound"
            OnRowEditing="GridView1_RowEditing"
            OnRowDeleting="GridView1_RowDeleting"
            OnRowUpdating="GridView1_RowUpdating"
            OnRowCancelingEdit="GridView1_RowCancelingEdit"
            AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
        </asp:GridView>
        <%--<asp:SqlDataSource ID="dsCategory" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionStringSB %>" ProviderName="<%$ ConnectionStrings:ConnectionStringSB.ProviderName %>" SelectCommand="SELECT * FROM [category]"></asp:SqlDataSource>--%>
    </div>
</asp:Content>
