<%@ Page Language="C#" MasterPageFile="~/Site.Master" title="Customer"  AutoEventWireup="true" CodeBehind="Customer.aspx.cs" Inherits="ShadyBusiness.Customer" %>

<asp:Content ID="Customer" ContentPlaceHolderID="MainContent" runat="server">
    <div class="pt-3">
        <h3>Customer</h3>
        <div class="form-group">
            <label>Name</label>
            <asp:TextBox ID="txtName" runat="server" placeholder="Name" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Address</label>
            <asp:TextBox ID="txtAddress" runat="server" placeholder="Address" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Contact Number</label>
            <asp:TextBox ID="txtNumber" runat="server" placeholder="+977 XXXXXXXXXX" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Email address</label>
            <asp:TextBox ID="txtEmail" runat="server" placeholder="abc@email.com" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Member Type</label>
            <asp:TextBox ID="txtType" runat="server" placeholder="Premium" CssClass="form-control"></asp:TextBox>
        </div>
        <div>
            <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click" CssClass="btn btn-primary" />
        </div>
        <div>
            <asp:GridView ID="GridView1" CssClass="table table-hover" runat="server" DataKeyNames="member_number"
                EmptyDataText="No records has been added." 
                OnRowEditing="GridView1_RowEditing"
                OnRowDeleting="GridView1_RowDeleting"
                OnRowUpdating="GridView1_RowUpdating"
                OnRowDataBound="GridView1_RowDataBound"
                OnRowCancelingEdit="GridView1_RowCancelingEdit" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
            </asp:GridView>
        </div>
    </div>
</asp:Content>
