<%@ Page Language="C#" MasterPageFile="~/Site.Master" title="Customer"  AutoEventWireup="true" CodeBehind="Customer.aspx.cs" Inherits="ShadyBusiness.Customer" %>

<asp:Content ID="Customer" ContentPlaceHolderID="MainContent" runat="server">
    <div class="pt-3">
        <h3>Membership Form </h3><br />
        <div class="form-row">
        <div  class="form-group col-md-12">
            <label>Name</label>
            <asp:TextBox ID="txtName" runat="server" placeholder="Name" class="form-control"></asp:TextBox>
        </div>
        <div  class="form-group col-md-12">
            <label>Address</label>
            <asp:TextBox ID="txtAddress" runat="server" placeholder="Address" class="form-control"></asp:TextBox>
        </div>
        <div  class="form-group col-md-4">
            <label>Contact Number</label>
            <asp:TextBox ID="txtNumber" runat="server" placeholder="+977 XXXXXXXXXX" class="form-control"></asp:TextBox>
        </div>
        <div  class="form-group col-md-4">
            <label>Email address</label>
            <asp:TextBox ID="txtEmail" runat="server" placeholder="abc@email.com" class="form-control"></asp:TextBox>
        </div>
        <div class="form-group col-md-4">
            <label>Member Type</label>
            <asp:TextBox ID="txtType" runat="server" placeholder="Premium" class="form-control"></asp:TextBox>
        </div>
        </div>
        <div>
            <asp:Button ID="btnAdd" runat="server" Text="     ADD CUSTOMER     " OnClick="btnAdd_Click" CssClass="btn btn-primary float-right" />
        </div>
        <br /><br /><hr/><br />
        <b style="font-size:24px;">View Customers</b><br /><br />
        <div>
            <asp:GridView ID="GridView1" CssClass="table table-striped  table-bordered" runat="server" DataKeyNames="member_number"
                EmptyDataText="No records has been added." 
                OnRowEditing="GridView1_RowEditing"
                OnRowDeleting="GridView1_RowDeleting"
                OnRowUpdating="GridView1_RowUpdating"
                OnRowDataBound="GridView1_RowDataBound"
                OnRowCancelingEdit="GridView1_RowCancelingEdit" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
            </asp:GridView>
        </div>
    </div>
</asp:Content>
