<%@ Page Language="C#" MasterPageFile="~/Site.Master" title="PurchaseList" AutoEventWireup="true" CodeBehind="PurchaseList.aspx.cs" Inherits="ShadyBusiness.PurchaseList" %>

<asp:Content ID="Purchaser" ContentPlaceHolderID="MainContent" runat="server">
    <br/>


        <b style="font-size:24px;">Purchase List:</b>
         <asp:Button ID="Button1"  class="btn btn-primary float-right" runat="server" Text="Add Purchase" OnClick="btnAddPurchase_Click" /><br/><br/>
        <asp:GridView ID="GridView1" 
                      class="table table-striped  table-bordered"
                      runat="server" 
                        OnRowDeleting="GridView1_RowDeleting"
                      OnSelectedIndexChanged="GridView1_SelectedIndexChanged"
                      EmptyDataText="No records has been added."
                    AutoGenerateSelectButton="True" 
            AutoGenerateDeleteButton="true"
         DataKeyNames="Purchase ID"
            OnRowDataBound ="GridView1_RowDataBound"
                      ></asp:GridView>
</asp:Content>