<%@ Page Language="C#" MasterPageFile="~/Site.Master" title="PurchaseList" AutoEventWireup="true" CodeBehind="PurchaseList.aspx.cs" Inherits="ShadyBusiness.PurchaseList" %>

<asp:Content ID="Purchaser" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Button ID="btnAddPurchase" runat="server" Text="Add Purchase" OnClick="btnAddPurchase_Click" />
        <asp:GridView ID="GridView1" 
                      class="table table-striped  table-bordered"
                      runat="server" 
                        OnRowDeleting="GridView1_RowDeleting"
                      OnSelectedIndexChanged="GridView1_SelectedIndexChanged"                          
                      EmptyDataText="No records has been added."
                    AutoGenerateSelectButton="True" 
            AutoGenerateDeleteButton="true"
         DataKeyNames="Purchase ID"
            OnRowDataBound ="GridView1_RowDataBound"
                      ></asp:GridView>
</asp:Content>