<%@ Page Language="C#" MasterPageFile="~/Site.Master" title="Staff" AutoEventWireup="true" CodeBehind="Staff.aspx.cs" Inherits="ShadyBusiness.Staff" %>

<asp:Content ID="Items" ContentPlaceHolderID="MainContent" runat="server">
    <div class="pt-3">
        <h3>Staff</h3>
        <div class="form-group">
            <label>Name</label>
            <asp:TextBox ID="txtName" runat="server" placeholder="Full Name"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Email</label>
            <asp:TextBox ID="txtEmail" runat="server" placeholder="Email"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Password</label>
            <asp:TextBox ID="txtPassword" runat="server" placeholder="Password"></asp:TextBox>
        </div>
       
        
        <asp:Button ID="btnInsert" runat="server" Text="Insert" CssClass="btn btn-primary" OnClick="btnInsert_Click" />
    </div>
    <div>
        <asp:GridView ID="GridView1" CssClass="table table-hover" runat="server"
            DataKeyNames="user_id"
            EmptyDataText="No records has been added."
            OnRowDataBound="GridView1_RowDataBound"
            OnRowEditing="GridView1_RowEditing"
            OnRowDeleting="GridView1_RowDeleting"
            OnRowUpdating="GridView1_RowUpdating"
            OnRowCancelingEdit="GridView1_RowCancelingEdit"
              AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" 
            >
        </asp:GridView>
    </div>
    
</asp:Content>