//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadyBusiness.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_item
    {
        public int purchase_id { get; set; }
        public int item_code { get; set; }
        public int purchase_unit { get; set; }
        public int line_total { get; set; }
    
        public virtual item item { get; set; }
        public virtual purchase purchase { get; set; }
    }
}
